
	<section id="blog">

		<? if(!isset($item->id)){ ?>
			<? $img->foto = 'foto_7'; ?>

            <div class="text-center bg-image" style="background: url('https://mdbcdn.b-cdn.net/img/new/slides/041.webp') no-repeat; background-size:cover;  height: 400px;">
                <div class="mask" style="background-color: rgba(0, 0, 0, 0.6); width: 100%; height: 100%;">
                    <div class="d-flex justify-content-center align-items-center h-100 hero">
                        <div class="text-white">
                            <h1 class="mb-3"><?=$textos[6]->nome_7?></h1>
                            <h2 class="subtitle mb-3"><?=$textos[6]->txt_7?></h2>
<!--                            <a class="btn btn-hero" href="#!" role="button">Saiba mais</a>-->
                        </div>
                    </div>
                </div>
            </div>



            <div class="container home-itens">
                <div class="row">
                    <? foreach ($blogs as $key => $value) { ?>

                    <div class="col-sm-12 col-md-4">
                        <div class="item">

                            <a href="<?=url('doacao', $value)?>">
                                <div class="item-image">

                                    <? $img->tags = ' class="" '; ?>
                                    <?=$img->img($value)?>
<!--                                                <img src="http://www.sonhosgarantidos.com.br/web/fotos/thumbnails/doacoes_17_autem-rerum-ab-est-s_sonhosgarantidos.com.br_zzb1dd5c9013_400x250.webp" title="Autem rerum ab est s" alt="Autem rerum ab est s" name="Autem rerum ab est s">-->


                                </div>
                                <div class="item-card">
                                    <h2 class="item-title"><?=$value->nome?></h2>
                                    <p class="item-description"><?=truncateString($value->txt,150)?></p>
                                    <div class="pt20 tac">
                                        <div class="btn btn-item">Mais detalhes</div>
                                    </div>
                                </div>
                            </a>

                        </div>
                    </div>

                    <? } ?>
                </div>
            </div>


		<? } else { ?>

			<? $img->foto = 'foto1'; ?>
			<div class="" style="background: url(<?=$img->img($item, 0, 0, 1)?>)">
				<div class="centerr">
					<div class="h100"></div>
					<div class="h60"></div>
					<div class="cor_fff">
						<div class="pt20 fz16 lh24"><?=$item->data1!='0000-00-00' ? data($item->data1) : ''?> <?=$item->autor ? 'Escrito por: '.$item->autor : ''?></div>
			            <div class="pt10 fz40 fwb"><?=$item->nome?></div>
			        </div>
			        <div class="h60"></div>
			    </div>
			</div>

            <section class="container text">
                <div class="row justify-content-md-center">
                    <div class="col-md-10">
                        <?=txt($item)?>
                    </div>
                </div>
            </section>


            <div class="container home-itens">
                <div class="row">
                    <div class="col">
                        <h1>ÚLTIMAS NOTÍCIAS</h1>
                    </div>
                </div>
                <div class="row">
                    <? foreach ($blogs as $key => $value) { ?>

                        <div class="col-sm-12 col-md-4">
                            <div class="item">

                                <a href="<?=url('doacao', $value)?>">
                                    <div class="item-image">

                                        <? $img->tags = ' class="" '; ?>
                                        <?=$img->img($value)?>
                                        <!--                                                <img src="http://www.sonhosgarantidos.com.br/web/fotos/thumbnails/doacoes_17_autem-rerum-ab-est-s_sonhosgarantidos.com.br_zzb1dd5c9013_400x250.webp" title="Autem rerum ab est s" alt="Autem rerum ab est s" name="Autem rerum ab est s">-->


                                    </div>
                                    <div class="item-card">
                                        <h2 class="item-title"><?=$value->nome?></h2>
                                        <p class="item-description"><?=truncateString($value->txt,150)?></p>
                                        <div class="pt20 tac">
                                            <div class="btn btn-item">Mais detalhes</div>
                                        </div>
                                    </div>
                                </a>

                            </div>
                        </div>

                    <? } ?>
                </div>
            </div>


		<? } ?>


	</section>
