
	<section id="cadastro">

        <div class="container">

            <div class="row">
                <div class="col">
                    <h1 class="page-title">CADASTRE-SE</h1>
                </div>
            </div>

            <div class="row justify-content-md-center mt-5">

                <form id="form_cadastro" class="col-md-6 col-sm-12" method="post" action="">

                    <div class="row">
                        <div class="col">
                            <label>Nome</label>
                            <input type="text" name="nome" class="form-control" placeholder="Digite aqui" required>
                        </div>
                    </div>

                    <div class="row">
                        <div class="col">
                            <label>CPF</label>
                            <input type="text" name="cpf" class="cpf form-control" placeholder="Digite aqui" required>
                        </div>
                    </div>

                    <div class="row">
                        <div class="col">
                            <label>Email</label>
                            <input type="email" name="email" class="form-control" placeholder="Digite aqui" required autocomplete="off">
                        </div>
                    </div>

                    <div class="row">
                        <div class="col">
                            <label>Telefone</label>
                            <input type="tel" name="telefone" class="form-control" placeholder="Digite aqui" required>
                        </div>
                    </div>

                    <div class="row">
                        <div class="col">
                            <label>Cep*</label>
                            <input type="text" name="cep" id="cep" class="form-control" placeholder="Digite aqui" required onblur="cepp(this)" required autocomplete="off">
                        </div>
                    </div>

                    <div class="row">
                        <div class="col">
                            <label>Endereço*</label>
                            <input type="text" name="rua" id="rua" class="form-control" placeholder="Digite aqui" required  autocomplete="off">
                        </div>
                    </div>

                    <div class="row">
                        <div class="col">
                            <label>Número*</label>
                            <input type="text" name="numero" id="numero" class="form-control" placeholder="Digite aqui" required autocomplete="off">
                        </div>
                    </div>

                    <div class="row">
                        <div class="col">
                            <label>Complemento</label>
                            <input type="text" name="complemento" id="complemento" class="form-control" placeholder="Digite aqui" autocomplete="off">
                        </div>
                    </div>

                    <div class="row">
                        <div class="col">
                            <label>Bairro*</label>
                            <input type="text" name="bairro" id="bairro" class="form-control" placeholder="Digite aqui" required autocomplete="off">
                        </div>
                    </div>

                    <div class="row">
                        <div class="col">
                            <label>Estados*</label>
                            <select name="estados" id="estados" class="form-control" required rel_estados="cidades" onchange="rel_estados(this)">
                                <option value=""> - - - </option>
                                <?
                                    if(file_exists(DIR_F.'/plugins/Json/localidades/estados.json')){
                                        $json = json_decode(file_get_contents(DIR_F.'/plugins/Json/localidades/estados.json'));
                                        foreach($json as $value){
                                            echo '<option value="'.$value->sigla.'"> ';
                                                echo $value->nome;
                                            echo '</option> ';
                                        }
                                    }
                                ?>
                            </select>
                        </div>
                    </div>

                    <div class="row">
                        <div class="col">
                            <label>Cidades*</label>
                            <select name="cidades" id="cidades" class="form-control" required>
                                <option value=""> - - - </option>
                            </select>
                        </div>
                    </div>
                    <style>.select2-selection__rendered { font-size: 12px !important; } </style>

                    <div class="row">
                        <div class="col">
                            <label>Pix (tipo):</label>
                            <select name="pix_tipo" id="pix_tipo" class="form-control">
                                <option value="0"> - - - - </option>
                                <option value="1">CPF/CNPJ</option>
                                <option value="2">Celular</option>
                                <option value="3">Email</option>
                                <option value="4">Aleatório</option>
                            </select>
                        </div>
                    </div>

                    <div class="row">
                        <div class="col">
                            <label>Pix (Chave):</label>
                            <input type="text" name="pix_chave" class="form-control">
                        </div>
                    <div>

                    <div class="remove_edit">
                        <div class="row">
                            <div class="col">
                                <label>Senha</label>
                                <input type="password" name="senha" class="form-control" placeholder="Digite aqui" required autocomplete="off">
                            </div>
                        </div>
                        <div class="row">
                            <div class="col">
                                <label>Confirmar a Senha</label>
                                <input type="password" name="c_senha" class="form-control" placeholder="Digite aqui" required>
                            </div>
                        </div>

                    </div>

                    <div class="row">
                        <div class="col termos">
                            <label>
                                <input type="checkbox" name="termos" value="1" required>
                                Eu aceito os <a href="<?=DIR?>/textos/<?=amg(1)?>/1/" target="_blank" class="link c_azul">Termos de Uso</a>.
                            </label>
                        </div>
                    </div>

                    <div class="row">
                        <div class="col">
                            <button class="btn-send">Cadastrar</button>
                        </div>
                    </div>

                    <? if(isset($_GET['nome'])){ ?>
                        <? $url = $_GET['nome'] ?>
                        <? $url .= $_GET['id']!='-' ? '/'.$_GET['id'] : ($_GET['categorias']!='-' ? '/-' : ''); ?>
                        <? $url .= $_GET['categorias']!='-' ? '/'.$_GET['categorias'] : ''; ?>
                        <input type="hidden" name="direcionar" value="<?=$url?>" />
                    <? } ?>

                    <input type="hidden" name="gravar" value="1">
                </form>


            </div>
        </div>
            <script>ajaxForm('form_cadastro', 'cadastro.php')</script>



	        <style>.carregando_endereco { display: none !important; }</style>

	</section>

