
	<section id="texto">

        <div class="container mt-5">
            <div class="row">
                <h1>DOAÇÕES</h1>
                <? if(isset($_GET['busca'])){?>
                    <h2 class="lead">Buscando por: <?=$_GET['busca']?></h2>
                <? } ?>

            </div>
        </div>

        <div class="container home-itens">
            <div class="row">
                <? foreach ($doacoes as $key => $value) { ?>
                    <div class="col-sm-12 col-md-4">
                        <div class="item">
                            <? include DIR_F.'/views/z_doacao.phtml'; ?>
                        </div>
                    </div>
                <? } ?>
            </div>
        </div>

	</section>
