
	<section id="doacao">

        <?
        $porc = doacoes_feitas_porc($item);
        if($porc > 100){
            $barraporc = 100;
        }else{
            $barraporc = $porc;
        }
        ?>

        <? $img->foto = 'foto1'; ?>


        <div class="container doacao-hero">
            <div class="row">
                <div class="col">
                    <h1 class=""><?=$item->nome?></h1>
                    <p><?=truncateString($item->txt,150)?></p>
                </div>
            </div>
        </div>

        <div class="container doacao-content">
            <div class="row">
                <div class="col-md-7">
                    <div class="doacao-img" style="background:url(<?=$img->img($item, 0, 0, 1)?>) no-repeat center; background-size: cover"></div>
                </div>
                <div class="col">
                    <div class="item-card">
                        <small>Sonho: <?=$item->uniqid?></small>
                        <div class="pt5">
                            <div class="item-bar">
                                    <div class="item-bar-fill w<?=$barraporc?>p"></div>
<!--                                <div class="item-bar-fill w50p"></div>-->
                                <div class="item-bar-border"></div>
                            </div>
                            <div class="item-percentage"><?=$porc?>%</div>
                        </div>
                        <div class="">
                            <div class="doacoes-arrecadados"><?=doacoes_feitas($item);?></div>
                            <small>arrecadados</small>
                            <div class="doacoes-meta"><?=doacoes_meta($item);?></div>
                            <small>meta</small>
                            <div class="doacoes-total"><?=doacoes_total($item);?></div>
                            <small>apoiadores</small>
                        </div>
                        <div class="col">
                            <a href="<?=url('doacao_pagamento', $item)?>" class="btn btn-doar">Doar</a>
                        </div>
                        <div class="col">
                            <div class="dropdown">
                                <button class="btn btn-share dropdown-toggle" id="dropdownMenuButton" data-bs-toggle="dropdown" aria-expanded="false">
                                    <svg xmlns="http://www.w3.org/2000/svg" height="1em" viewBox="0 0 448 512">
                                    <path d="M352 224c53 0 96-43 96-96s-43-96-96-96s-96 43-96 96c0 4 .2 8 .7 11.9l-94.1 47C145.4 170.2 121.9 160 96 160c-53 0-96 43-96 96s43 96 96 96c25.9 0 49.4-10.2 66.6-26.9l94.1 47c-.5 3.9-.7 7.8-.7 11.9c0 53 43 96 96 96s96-43 96-96s-43-96-96-96c-25.9 0-49.4 10.2-66.6 26.9l-94.1-47c.5-3.9 .7-7.8 .7-11.9s-.2-8-.7-11.9l94.1-47C302.6 213.8 326.1 224 352 224z"/></svg>
                                    Compartilhar
                                </button>
                                <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                                    <ul class="a2a_kit a2a_kit_size_32 a2a_default_style">
                                        <li><a class="a2a_button_facebook"></a></li>
                                        <li><a class="a2a_button_twitter"></a></li>
                                        <li><a class="a2a_button_pinterest"></a></li>
                                        <li><a class="a2a_dd" href="https://www.addtoany.com/share"></a></li>
                                    </ul>
                                </div>
                            </div>
                            <script async src="https://static.addtoany.com/menu/page.js"></script>
                        </div>
                    </div>
                </div>
            </div><!-- row -->
            <div class="row">

            </div>
        </div><!-- container -->

		<div class="container doacao-tabs" >
			<div class="">
				<div class="tabs">
					<div class="fz20 tac flexx flex_c flex_ac">
						<div onclick="txt_(0)" class="tab txt__ txt__0 p10 c-p flex_1 bdb_ccc ativo">Sobre</div>
						<div onclick="txt_(1)" class="tab txt__ txt__1 p10 c-p flex_1 bdb_ccc">Quem Ajudou</div>
					</div>
					<div class="tab-content p40 fz16 lh24">
						<div class="txt_ txt_0"><?=$item->txt1?></div>
						<div class="dn txt_ txt_1">
							<?
				    	        $mysql->filtro = " WHERE ".STATUS." AND `doacoes` = '".$item->id."' ";
					            $doacoes_pagamentos = $mysql->read('doacoes_pagamentos');
					        ?>
				            <table class="w100p">
				                <tr>
				                    <td class="p10 fz12 lh14 bdt_eee bdb_eee bdl_eee">
				                        <div class="fwb">Nome</div>
				                    </td>
				                    <td class="p10 fz12 tac bdt_eee bdb_eee bdl_eee">
				                        <div class="fwb">Valor</div>
				                    </td>
				                    <td class="p10 fz12 tac bdt_eee bdb_eee bdl_eee">
				                        <div class="fwb">Status</div>
				                    </td>
				                </tr>
				                <? foreach ($doacoes_pagamentos as $key => $value) { ?>
				                    <tr>
				                        <td class="p10 fz12 lh14 bdt_eee bdb_eee bdl_eee">
				                            <div class="pt5"><?=rel('cadastro', $value->cadastro)?></div>
				                        </td>
				                        <td class="p10 fz12 lh14 tac bdt_eee bdb_eee bdl_eee">
				                            <div class="pt5"><?=preco($value->preco, 1)?></div>
				                        </td>
				                        <td class="p10 fz12 lh14 tac bdt_eee bdb_eee bdl_eee bdr_eee">
				                            <div class="pt5"><?=doacoes_situacao($value->situacao)?></div>
				                        </td>
				                    </tr>
				                <? } ?>
				                <? if(!$doacoes_pagamentos){ ?>
				                    <tr>
				                        <td colspan="5" class="p10 fz12 lh14 tac bdt_eee bdb_eee bdl_eee">
				                        	<div class="">Nenhuma doação encontrada...</div>
				                        </td>
				                    </tr>
				                <? } ?>
				            </table>
						</div>
					</div>
				</div>
			</div>
		</div>


		<style>
			#doacao .ativo { font-weight: bold; border-bottom: 1px solid #<?=COR1?>; }
		</style>
		<script>
			function txt_($x){
				$('.txt_').hide();
				$('.txt_'+$x).show();
				$('.txt__').removeClass('ativo')
				$('.txt__'+$x).addClass('ativo')
			}
		</script>



	</section>
