
	<section id="fale">

		<? $img->foto = 'foto_9'; ?>
		<div class="" style="background: url(<?=$img->img($textos[6], 0, 0, 1)?>) center;">
			<div class="centerr">
				<div class="h100"></div>
				<div class="h60"></div>
				<div class="cor_fff">
					<div class="pt20 fz40 fwb"><?=$textos[6]->nome_9?></div>
		            <div class="pt10 fz16 lh24"><?=$textos[6]->txt_9?></div>
		        </div>
		        <div class="h60"></div>
		    </div>
		</div>


		<div class="pt60 pb60">
			<div class="centerr1">
				<div class="">
					<form id="formAjax1" method="post" action="" enctype="multipart/form-data" >
						<input name="to" type="hidden" value="<?=$emails->email?>" />
						<input name="assunto" type="hidden" value="Contato" />

						<div class="">
							<div class="fz16 fwb">Nome Completo</div>
							<div class="pt5">
								<input type="text" name="mail[campo][]" class="design w100p" placeholder="Digite aqui" required /> 
								<input type="hidden" name="mail[nome][]" value="Nome" />
							</div>
						</div>

						<div class="wr6 mt20">
							<div class="fz16 fwb">Email</div>
							<div class="pt5">
								<input type="email" name="mail[campo][]" class="design w100p" placeholder="Digite aqui" required /> 
								<input type="hidden" name="mail[nome][]" value="Email" />
							</div>
						</div>

						<div class="wr6 mt20 pl20 p0_1000">
							<div class="fz16 fwb">Telefone</div>
							<div class="pt5">
								<input type="text" name="mail[campo][]" class="design w100p" placeholder="Digite aqui" required /> 
								<input type="hidden" name="mail[nome][]" value="Nome" />
							</div>
						</div>
						<div class="clear"></div>

						<div class="mt20">
							<div class="fz16 fwb">Mensagem</div>
							<div class="pt5">
					            <textarea name="mail[campo][]" class="design w100p h150" placeholder="Digite aqui"></textarea>
								<input type="hidden" name="mail[nome][]" value="Mensagem" />
							</div>
						</div>

						<div class="pt20 tar">
							<button class="dib p10 pl60 pr60 fz20 fwb cor_fff bd0 back_<?=COR1?> br20">Enviar</button>
						</div>

						<input type="reset" class="dni">
						<input type="hidden" name="log_gravacoes" value="1" />

					</form>
					<script>ajaxForm('formAjax1', 'mail.php')</script>
				</div>
				<div class="clear"></div>
			</div>
		</div>

	</section>
