
	<section id="faq">

        <div class="container">
            <div class="row justify-content-md-center">
                <div class="col-12">
                    <h1>DÚVIDAS FREQUENTES</h1>
                </div>
            </div>
            <div class="row justify-content-md-center">
                <div class="col-8">
                    <h2 class="lead">Está com dúvidas em como a plataforma funciona? Leia abaixo!</h2>
                </div>
            </div>
        </div>

        <div class="container" style="margin-top:85px;">
            <div class="row justify-content-md-center">
                <div class="col-md-8 col-sm-12">
                    <div class="faq">
                        <? foreach ($faq as $key => $value) { ?>
                            <div onclick="faq(this)" class="pb20 c-p <?=!$key ? 'ativo' : ''?>">
                                <div class="p30 bd_f4f4f4 back_fff br5 bs1">
                                    <div class="posr">
                                        <div class="fz24 fwb nomee"><?=$value->nome?></div>
                                        <div class="posa t0 r0 w50 h100p fz28 c_flex jc">
                                            <i class="faa-angle-up"></i>
                                            <i class="faa-angle-down"></i>
                                        </div>
                                    </div>
                                    <div class="pt20 fz16 lh24 txt">
                                        <?=$value->txt?>
                                    </div>
                                </div>
                            </div>
                        <? } ?>
                    </div>
                </div>
            </div>
        </div>


        <style>
            .faq .txt { display: none; }
            .faq .ativo .txt { display: block; }

            .faq .ativo .nomee { color: #<?=COR1?> }

            .faq .faa-angle-up { display: none; }
            .faq .faa-angle-down { display: block; }
            .faq .ativo .faa-angle-up { display: block; }
            .faq .ativo .faa-angle-down { display: none; }
        </style>
        <script>
            function faq(e){
                $('.faq .ativo').removeClass('ativo');
                $(e).addClass('ativo');
            }
        </script>

	</section>
