
	<section id="home">

		<? if(isset($banner[1])){ ?>
            <!-- Background image -->
            <div class="text-center bg-image">
                <img src="<?=DIR?>/web/img/banner-sonhos.png" style="max-width: 100%;">
            </div>
            <!-- Background image -->
		<? } ?>

		<div class="container home-itens">
            <div class="row">
                <? foreach ($doacoes as $key => $value) { ?>
                    <div class="col-sm-12 col-md-4">
                        <div class="item">
                            <? include DIR_F.'/views/z_doacao.phtml'; ?>
                        </div>
                    </div>
                <? } ?>
            </div>
		</div>

	</section>
