
    <script>
        <? if($_GET['pg'] == 'login'){ ?>
            $(document).ready(function(){
                $('.BOX_LOGIN').show();
            });
        <? } ?>
        <? if(isset($_GET['abrir']) AND $_GET['abrir']){ ?>
            $(document).ready(function(){
                $('.<?=$_GET['abrir']?>').show();
            });
        <? } ?>
    </script>



    <!-- LOGIN -->


                        <div id="login" class="container">

                            <div class="row">
                                <div class="col">
                                    <? if( !(isset($_GET['q']) and $_GET['q']) ){ ?>
                                        <h1 class="page-title">LOGIN</h1>
                                    <? }else { ?>
                                        <h1 class="page-title">RECUPERAR SENHA</h1>
                                    <?php } ?>
                                </div>
                            </div>

                                <?
                                    $url = DIR_D;
                                    $url = str_replace('/login/', '', $url);
                                    $url = str_replace('/login', '', $url);
                                ?>
                            <div class="row justify-content-md-center mt-5">

                                <? if( !(isset($_GET['q']) and $_GET['q']) ){ ?>

                                    <form id="form_login" class="col-md-6 col-sm-12" method="post" action="">

                                        <div class="row">
                                            <div class="col">
                                                <label for="email">E-mail</label>
                                                <input type="text" name="email" class="form-control" placeholder="seu@email.com" required>
                                            </div>
                                        </div>

                                        <div class="row">
                                            <div class="col">
                                                <label for="senha">Senha</label>
                                                <input type="password" name="senha" class="form-control" placeholder="********" required>
                                            </div>
                                        </div>

                                        <div class="row">
                                            <div class="col login-help">
                                                <a onclick="$('.BOX_LOGIN').hide(); $('.BOX_CADASTRO').show();" class="float-start">Cadastre-se</a>
                                                <a onclick="boxs('esqueci_senha')" class="float-end">Esqueceu sua senha?</a>
                                            </div>
                                        </div>

                                        <div class="row mt-5">
                                            <div class="col">
                                                <button class="btn-send">Login</button>
                                            </div>
                                        </div>

                                        <input type="hidden" name="direcionar" value="<?=$url?>" />
                                        <input type="hidden" name="fazer_login" value="1">
                                    </form>

                                <?php }else{ ?>

                                    <form action="" class="col-md-6 col-sm-12"  method="post">


                                        <div class="row">
                                            <div class="col">
                                                <label for="email">Nova Senha</label>
                                                <input type="password" name="senha" id="senha" class="form-control" placeholder="Nova Senha*" required/>
                                            </div>
                                        </div>

                                        <div class="row">
                                            <div class="col">
                                                <label for="senha">Confirmar Senha</label>
                                                <input type="password" name="c_senha" id="c_senha" class="form-control" placeholder="Confirmar Senha*" required/>
                                            </div>
                                        </div>

                                        <div class="row mt-5">
                                            <div class="col">
                                                <button type="submit" class="btn-send">Salvar</button>
                                            </div>
                                        </div>

                                        <BR><BR><BR><BR>
                                    </form>


                                <?php } ?>
                            </div><!--row-->

                            <script>ajaxForm('form_login', 'login.php')</script>

                        </div> <!--container -->


                    <div class="clear"></div>


                </div>
            </div>
        </div>
    <!-- LOGIN -->


    <!-- CADASTRO -->
        <div class="dn posa t0 l0 z9 w100p h100p BOX_CADASTRO">
            <div class="h30"></div>
            <div class="centerr1">
                <div class="p40 pt20 br15 back_fff bs1">

                    <div class="posr">
                        <a onclick="$('.BOX_CADASTRO').hide();" class="posa t0 r0 fz40 fwb">X</a>
                        <div class="fz50 fwb tac">Cadastrar</div>

                        <div class="pt40">
                            <?
                                if($_GET['pg'] != 'cadastro'){
                                    $_GET['include_cadsatroo'] = 1;
                                }
                                include DIR_F.'/views/cadastro.phtml';
                            ?>
                            <div class="clear"></div>
                        </div>
                    </div>
                    <div class="clear"></div>


                </div>
            </div>
        </div>
    <!-- CADASTRO -->

