
    <?
        $porc = doacoes_feitas_porc($value);
        if($porc >= 100){
            $barraporc = 100;
        }else{
            $barraporc = $porc;
        }
    ?>

    <a href="<?=url('doacao', $value)?>">
        <div class="item-image">

            <? $img->tags = ' class="" '; ?>
            <?=$img->img($value)?>
<!--            <img src="http://www.sonhosgarantidos.com.br/web/fotos/thumbnails/doacoes_17_autem-rerum-ab-est-s_sonhosgarantidos.com.br_zzb1dd5c9013_400x250.webp" title="Autem rerum ab est s" alt="Autem rerum ab est s" name="Autem rerum ab est s">-->


        </div>
        <div class="item-card" style="color:#ccc; font-size: 12px;">
            <small>Sonho: <?=$value->uniqid?></small>
            <h2 class="item-title"><?=$value->nome?></h2>
            <p class="item-description">
                <?=truncateString($value->txt,150)?></p>
            <div class="pt5">
                <div class="item-bar">
                    <div class="item-bar-fill w<?=$barraporc?>p"></div>
<!--                    <div class="item-bar-fill w50p"></div>-->
                    <div class="item-bar-border"></div>
                </div>
                <div class="item-percentage"><?=$porc?>%</div>
            </div>
            <div class="pt20 tac">
                <div class="btn btn-item">Mais detalhes</div>
            </div>
        </div>
    </a>
