<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.min.js" integrity="sha384-cuYeSxntonz0PPNlHhBs68uyIAVpIIOZZ5JqeqvYYIcEL727kskC66kF92t6Xl2V" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4" crossorigin="anonymous"></script>

<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Open+Sans:wght@300;400;700;800&family=Poppins:wght@100;400;700&display=swap" rel="stylesheet">

<style>
    h1{
        color: #E8AD69;
        text-align: center;
        font-size: 40px;
        font-family: "Poppins";
        font-style: normal;
        font-weight: 400;
        line-height: 72px;
        letter-spacing: -0.25px;
    }
    #home, #doacao{
        background: #F7F5E8;
    }
    #doacao{
        padding-bottom:90px;
    }

    .navbar-light{
        background:#F7F5E8 !important;
        box-shadow: -1px -1px 35px 0px rgba(0,0,0,0.21);
        -webkit-box-shadow: -1px -1px 35px 0px rgba(0,0,0,0.21);
        -moz-box-shadow: -1px -1px 35px 0px rgba(0,0,0,0.21);
    }
    .navbar-brand{
        max-width: 235px;
    }
    .searchform{
        min-width: 50%;
    }
    .search{
        border:none;
        border-radius: 10px;
        color: #E8AD69;
        padding:12px 16px;
        min-width: 50%;
        font-family: "Open Sans", Sans-Serif !important;
        font-size:14px !important;
    }
    .search-group{
        margin: 0 10%;
    }
    .search::placeholder {
        color: #E8AD69; /* Define a cor do texto do placeholder */
    }
    .search:focus{
        border:1px solid #E8AD69;
    }
    .nav-link{
        color:#C6945B !important;
        font-family: "Open Sans", Sans-Serif !important;
        font-size:14px !important;
        padding:0 20px;
        text-align: center;
    }
    .btn-header{
        display: flex;
        padding: 12px 16px;
        justify-content: center;
        align-items: center;
        gap: 6px;
        border-radius: 12px;
        color:white;
        background: linear-gradient(89deg, #6E9ECF 0%, #C39BD3 100%);
        animation: all 2s linear;
    }
   .btn-header:hover{
       background: linear-gradient(89deg, #6E9ECF 100%, #C39BD3 200%);
       color:white !important;
   }
   .hero{
       display: flex;
       align-content: flex-start;
   }
   .hero h1{
       display: flex;
       width: 880px;
       flex-direction: column;
       flex-shrink: 0;
       color: #FFF;
       font-size: 64px;
       font-family: Poppins;
       font-weight: 700;
       line-height: 72px;
       letter-spacing: -0.25px;
       text-align: left;
   }
   .hero .btn-hero{
       display: flex;
       width: 209px;
       height: 67px;
       padding: 4px 12px;
       flex-direction: column;
       justify-content: center;
       align-items: center;
       gap: 6px;
       flex-shrink: 0;
       padding: 4px 12px;
       border-radius: 16px;
       background: #E8AD69;
       max-width: 200px;
       text-align: center;
       color: #FFF;
       font-size: 20px;
       font-family: "Open Sans";
       line-height: 20px;
       letter-spacing: 0.2px;
   }
    .home-itens{
        margin-top:108px;
    }

    .home-itens .item{
        margin-bottom:50px;
        border-radius: 8px;
        background:#fff;
    }

    .home-itens .item-image img{
        border-radius: 8px 8px 0px 0px;
        width: 100%;
    }

    .home-itens .item-card{
        border-radius: 8px 8px 0px 0px;
        padding:20px;
    }

    .item-title{
        color: #E8AD69;
        font-size: 22px;
        font-family: Poppins;
        font-style: normal;
        font-weight: 700;
        line-height: 28px;
        letter-spacing: 0.088px;
    }

    .item-description{
        color: #8F8F8F;
        font-size: 14px;
        font-family: "Open Sans";
        font-style: normal;
        font-weight: 400;
        line-height: 20px;
        letter-spacing: 0.08px;
        margin-bottom: 30px;
    }

    .item-bar{
        width: 83%;
        position: relative;
        float:left;
        margin: 0px 10px 0px 0px;
    }
    .item-bar-border{
        height: 13px;
        flex-shrink: 0;
        border-radius: 8px;
        border: 1px solid #759ED0;
        background: linear-gradient(90deg, rgba(113, 159, 208, 0.00) 0%, rgba(193, 156, 211, 0.00) 100%);
    }
    .item-bar-fill{
        height: 13px;
        border-radius: 8px;
        border: 1px solid #9A9A9A;
        background: linear-gradient(90deg, #709FD0 0%, #C39CD4 100%);
        position:absolute;
    }
    .item-percentage{
        color: var(--black, #000);
        font-size: 14px;
        font-family: "Open Sans";
        font-style: normal;
        font-weight: 700;
        letter-spacing: 0.08px;
        line-height: 10px;
    }

    .btn-item{
        display: flex;
        width: 139.458px;
        height: 45.073px;
        padding: 4px 12px;
        flex-direction: column;
        justify-content: center;
        align-items: center;
        gap: 6px;
        flex-shrink: 0;
        border-radius: 16px;
        background: #E8AD69;
        color: var(--white, #FFF);
        font-size: 12px;
        font-family: "Open Sans";
        font-style: normal;
        font-weight: 400;
        line-height: 16px;
        letter-spacing: 0.2px;
        margin:30px auto 0 auto;
    }

    footer{
        background: #CEA575;
        color:#fff;
        padding:50px;
    }

    footer .address{
        color: #FFF;
        font-size: 14px;
        font-family: "Open Sans";
        font-style: normal;
        font-weight: 100;
        letter-spacing: 0.08px;
        margin-top:15px;
    }

    footer .social{
        margin-top:18px;
    }

    footer p{
        margin-bottom:0;
    }

    .footer-menu{
        color:white;
        line-height: 10px;
        border-left: 1px solid white;
        padding-left:10px;
        margin-left:100px;
        margin-top:20px;
    }

    .footer-menu li{
        margin-bottom:20px;
    }

    .footer-menu li a{
        color: #FFF;
        font-size: 15px;
        font-family: "Open Sans";
        font-style: normal;
        font-weight: 400;
    }

    .credit{
        color: #FFF;
        font-size: 14px;
        font-family: "Open Sans";
        font-style: normal;
        font-weight: 400;
        line-height: 20px;
        letter-spacing: 0.08px;
        text-align: center;
        margin-top:22px;
    }

    .newsletter-input{
        height: 48px;
        border-radius: 8px 0px 0px 8px;
        background: #FFF;
        border:none;
        font-size:15px !important;
    }

    .btn-newsletter{
        display: flex;
        width: 127px;
        height: 48px;
        padding: 4px 12px;
        flex-direction: column;
        justify-content: center;
        align-items: center;
        gap: 6px;
        flex-shrink: 0;
        border-radius: 0px 8px 8px 0px;
        background: var(--transparent, rgba(0, 0, 0, 0.50));
        color:white;
    }
    .doacao-hero h1{
        margin-top:90px;
    }
    .doacao-hero p{
        display: flex;
        max-width: 879px;
        flex-direction: column;
        flex-shrink: 0;
        color: #838383;
        text-align: center;
        font-size: 40px;
        font-family: "Open Sans";
        font-style: normal;
        line-height: 48px;
        margin:auto;
        font-weight: 100;
        margin-top:44px;
    }
    .doacao-content{
        margin-top:111px;
    }
    .doacao-img{
        background-size: cover;
        height:500px;
        border-radius: 8px 8px 0px 0px;
    }
    .doacao-content .item-card{
        border-radius: 8px 8px 0px 0px;
        background: #FFF;
        padding:40px;
        height: 500px;
    }
    .doacao-content .doacoes-arrecadados{
        color: #4E9893;
        font-size: 32px;
        font-family: "Poppins";
        font-style: normal;
        font-weight: 700;
        line-height: 30px;
        margin-top:50px;
        m
    }
    .doacao-content .doacoes-meta {
        color: #E8AD69;
        font-size: 32px;
        font-family: "Poppins";
        font-style: normal;
        font-weight: 700;
        line-height: 30px;
        margin-top:25px;
    }
    .doacao-content .doacoes-total{
        color: #8D8D8D;
        font-size: 32px;
        font-family: "Poppins";
        font-style: normal;
        font-weight: 700;
        line-height: 30px;
        margin-top:25px;
    }
    .doacao-content small{
        color: #8D8D8D;
        font-size: 14px;
        font-family: "Open Sans";
        font-style: normal;
        font-weight: 400;
        line-height: 30px;
    }
    .doacao-content .btn-doar{
        margin-top:70px;
        display: flex;
        width: 173.987px;
        height: 45.073px;
        padding: 4px 12px;
        flex-direction: column;
        justify-content: center;
        align-items: center;
        gap: 6px;
        flex-shrink: 0;
        border-radius: 16px;
        background: #4E9893;
        color: var(--white, #FFF);
        font-size: 17px;
        font-family: "Open Sans";
        font-style: normal;
        font-weight: 400;
        line-height: 16px;
        letter-spacing: 0.2px;
        float:left;
    }
    .doacao-content .btn-share{
        margin-top:70px;
        display: flex;
        width: 210px;
        height: 45px;
        padding: 4px 12px;
        justify-content: center;
        align-items: center;
        gap: 6px;
        flex-shrink: 0;
        border-radius: 16px;
        border: 1px solid #739FD1;
        background: rgba(20, 16, 225, 0.00);
        color: #739FD1;
        font-size: 17px;
        font-family: "Open Sans";
        font-style: normal;
        font-weight: 400;
        line-height: 16px;
        letter-spacing: 0.2px;
        float:right;
    }
    .tabs .tab{
        font-family: "Poppins";
        font-style: normal;
        font-weight: 400!important;
        line-height: 20px;
        letter-spacing: 0.4px;
        border-radius: 8px 8px 0px 0px;
        border-bottom: 1.5px solid #E8AD69;
        background: rgba(227, 227, 227, 0.50);
        font-weight: 400!important;
        color: #E8AD69;
        border-radius:8px 8px 0 0;
        font-size: 14px;
    }
    .tabs .ativo{
        background: white;
        border-bottom:1px solid white !important;
    }
    .tab-content{
        border-radius: 0px 0px 8px 8px;
        background: #FFF;
        color: #737373;
        font-size: 16px;
        font-family: "Open Sans";
        font-style: normal;
        font-weight: 400;
        line-height: 24px;
    }
    .dropdown-menu{
        position: absolute;
        inset: 0px auto auto 0px;
        margin: 0px;
        transform: translate3d(236px, 137px, 0px);
        border-radius: 0 0 10px 10px;
        margin-top: -15px !important;
        border: 1px solid #739FD1;
        border-top: transparent;
        width: 210px !important;
        padding-top:20px;
    }

    #textos h1, #faq h1, #fale h1{
        color: #E8AD69;
        text-align: center;
        font-size: 64px;
        font-family: "Poppins";
        font-style: normal;
        font-weight: 400;
        line-height: 72px;
        letter-spacing: -0.25px;
        margin-top:90px;
        text-transform: uppercase;
    }

    #textos h2, #faq h2, #fale h2{
        color: #838383;
        text-align: center;
        font-size: 40px;
        font-family: Open Sans;
        font-style: normal;
        font-weight: 400;
        line-height: 48px;
        margin-top: 40px;
    }

    #textos .home-desc{
        color: #676767;
        font-size: 16px;
        font-family: "Open Sans";
        font-style: normal;
        font-weight: 400;
        line-height: 24px;
    }
    #textos .mvv{
        background: #F7F5E8;
        padding:80px 0 30px 0;
    }
    #textos .mvv .row{
        padding: 10px 100px 10px 100px;
        margin-bottom:50px;
    }
    #textos .mvv .valores{
        color: #709FD0;
        font-size: 25px;
        font-family: 'Poppins';
        font-style: normal;
        font-weight: 100;
        line-height: normal;
    }

    #textos .mvv .visao{
        color: #C39CD4;
        font-size: 25px;
        font-family: 'Poppins';
        font-style: normal;
        font-weight: 100;
        line-height: normal;
    }

    #textos .mvv .missao{
        color: #9B9DD2;
        font-size: 25px;
        font-family: 'Poppins';
        font-style: normal;
        font-weight: 100;
        line-height: normal;
    }

    .team-member-img{
        border-radius: 300px;
        width: 300px;
        height: 300px;
        margin:80px auto 50px auto;
        border: 2px solid #E8AD69;
        display:flex;
    }

    .team-member-name{
        color: #E8AD69;
        text-align: center;
        font-size: 25px;
        font-family: 'Poppins';
        font-style: normal;
        font-weight: 700;
        line-height: 24px;
    }

    .team-member-bio{
        color: #9F9F9F;
        text-align: center;
        font-size: 16px;
        font-family: 'Open Sans';
        font-style: normal;
        font-weight: 400;
        line-height: 24px;
        margin:30px auto 100px auto;
    }

    .text{
        color: #6D6D6D;
        font-size: 16px;
        font-family: Open Sans;
        font-style: normal;
        font-weight: 400;
        line-height: 24px;
        margin-top:120px;
        margin-bottom:120px;
    }

    #fale .form-control, #login .form-control, #cadastro .form-control{
        border-radius: 10px;
        border: 1px solid var(--subtle-2, #AFB1B6);
        padding: 30px 12px 10px 12px;
        align-items: flex-start;
        gap: 6px;
        margin-bottom: 25px;
        margin-top:-30px;
        color: var(--subtle-1, #61646B);

        /* body large */
        font-size: 16px;
        font-family: "Open Sans";
        font-style: normal;
        font-weight: 400;
        line-height: 24px;
    }

    #fale label, #login label, #cadastro label{
        color: var(--subtle-2, #AFB1B6);
        /* label small */
        font-size: 12px;
        font-family: "Open Sans";
        font-style: normal;
        font-weight: 500;
        line-height: 16px;
        letter-spacing: 0.6px;
        margin-left:13px;
    }

    .btn-send{
        border-radius: 16px;
        background: #E8AD69;
        display: flex;
        width: 138px;
        height: 45px;
        padding: 4px 12px;
        flex-direction: column;
        justify-content: center;
        align-items: center;
        gap: 6px;
        flex-shrink: 0;
        color:white;
        margin:auto;
        margin-bottom:80px;
        border:none;
    }

    #fale .social a{
        margin:0 22px;
    }

    .btn-search{
        background: white;
        border:none;
        color:#E8AD69;
        border-radius: 10px;
    }
    .btn-search:hover {
        color: #6E9ECF;
        background: white;
    }

    .login-help a{
        color: #000;

        /* label small */
        font-family: Work Sans;
        font-size: 12px;
        font-style: normal;
        font-weight: 500;
        line-height: 16px;
        letter-spacing: 0.6px;
    }

    .doacao-tabs{
        margin-top:100px
    }

    .page-title{
        margin-top:80px;
    }

    #blog .subtitle{
        text-align: left;
    }

    .navbar-mobile{
        display:none;
    }
    @media (max-width: 600px) {
        .navbar-brand {
            max-width: 80%;
            margin:10px auto 20px;
            padding:0;
        }
        .searchform{
            width: 100%;
        }
        .navbar-nav{
            display:none;
        }
        .navbar-mobile{
            display:flex;
            margin:auto;
            text-align: center;
            padding:0;
        }
        .btn-header{
            margin: 20px auto;
            width: 80%;
        }
        .hero h1{
            width: 80%;
            margin: 10px auto;
            font-size: 40px;
            line-height: 40px;
            text-align: center;
            margin-bottom: 50px !important;
        }
        .hero .btn-hero{
            margin:auto;
            height: 50px;
        }
        .home-itens{
            margin-top:30px;
        }
        .home-itens .item{
            margin-bottom:30px;
            margin-left:10px;
            margin-right:10px;
        }
        footer{
            padding:30px 20px;
            text-align: center;
        }
        .footer-menu{
            margin:50px;
            border:none;
        }
        .doacao-hero h1{
            margin-top:50px;
        }
        .doacao-content{
            margin-top:50px;
        }
        .doacao-content .btn-doar{
            margin-top:30px;
            width: 100%;
        }
        .doacao-content .btn-share{
            margin-top:20px;
            width: 100%;
        }
        .doacao-tabs{
            margin-top:30px
        }
        .page-title{
            margin-top:50px;
        }
        .termos{
            margin: 20px;
            text-align: center;
        }
        #textos .mvv .row{
            padding: 10px 10px 10px 10px;
            margin-bottom: 50px;
            text-align: center;
        }
        .team-member-img{
            margin:10px auto 10px auto;
        }
        #textos h1, #faq h1, #fale h1{
            font-size: 40px;
            line-height: 0;
            margin-top:50px;
        }
        .team-member-bio{
            margin:30px auto 30px auto;
        }
    }
</style>


    <header>
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <div class="container">
                <a class="navbar-brand" href="<?=DIR?>/"><img src="<?=DIR?>/web/img/logo.png" class="" /></a>
<!--                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">-->
<!--                    <span class="navbar-toggler-icon"></span>-->
<!--                </button>-->

                <form class="d-flex searchform" method="get" action="<?=DIR?>/doacoes/">
                    <div class="input-group search-group">
                        <input type="text" name="busca" class="form-control search" <?=isset($_GET['busca']) ? ' value="'.$_GET['busca'].'" ' : ' placeholder="Digite o número ou título para buscar" ';?>  />
                        <button class="btn btn-search" type="submit" id="button-addon2">
                            <svg xmlns="http://www.w3.org/2000/svg" height="1em" viewBox="0 0 512 512"><!--! Font Awesome Free 6.4.0 by @fontawesome - https://fontawesome.com License - https://fontawesome.com/license (Commercial License) Copyright 2023 Fonticons, Inc. --><path d="M416 208c0 45.9-14.9 88.3-40 122.7L502.6 457.4c12.5 12.5 12.5 32.8 0 45.3s-32.8 12.5-45.3 0L330.7 376c-34.4 25.2-76.8 40-122.7 40C93.1 416 0 322.9 0 208S93.1 0 208 0S416 93.1 416 208zM208 352a144 144 0 1 0 0-288 144 144 0 1 0 0 288z"/></svg>
                        </button>
                    </div>
                </form>

                <div class="collapse navbar-collapse d-flex" id="navbarSupportedContent">
                    <ul class="navbar-nav me-auto mb-2 mb-lg-0">

                        <? if(isset($_SESSION['x_site']->id)){ ?>
                            <li class="nav-item">
                                <a class="nav-link active" aria-current="page" href="/minha_conta">Minha Conta</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" onclick="ajaxNormal('ajaxForm/login.php?sair=1');">Sair</a>
                            </li>
                        <? } else { ?>
                            <li class="nav-item">
                                <a class="nav-link active" aria-current="page" href="/cadastro">Cadastre-se</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="/login">Login</a>
                            </li>
                        <? } ?>

                    </ul>
                </div>

                <a href="<?=DIR?>/login/minha_conta/meus_sonhos/criar_um_sonho" class="btn btn-header" style="color:white">
                    <svg xmlns="http://www.w3.org/2000/svg" height="1em" viewBox="0 0 640 512"><!--! Font Awesome Free 6.4.0 by @fontawesome - https://fontawesome.com License - https://fontawesome.com/license (Commercial License) Copyright 2023 Fonticons, Inc. --><path d="M0 336c0 79.5 64.5 144 144 144H512c70.7 0 128-57.3 128-128c0-61.9-44-113.6-102.4-125.4c4.1-10.7 6.4-22.4 6.4-34.6c0-53-43-96-96-96c-19.7 0-38.1 6-53.3 16.2C367 64.2 315.3 32 256 32C167.6 32 96 103.6 96 192c0 2.7 .1 5.4 .2 8.1C40.2 219.8 0 273.2 0 336z"/></svg>
                     Crie seu sonho</a>

                <ul class="navbar-mobile me-auto mb-2 mb-lg-0">

                    <? if(isset($_SESSION['x_site']->id)){ ?>
                        <li class="nav-item">
                            <a class="nav-link active" aria-current="page" href="/minha_conta">Minha Conta</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" onclick="ajaxNormal('ajaxForm/login.php?sair=1');">Sair</a>
                        </li>
                    <? } else { ?>
                        <li class="nav-item">
                            <a class="nav-link active" aria-current="page" href="/cadastro">Cadastre-se</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="/login">Login</a>
                        </li>
                    <? } ?>

                </ul>

            </div>
        </nav>
    </header>
